name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          docker pull lukasblecher/pix2tex:api
          nohup docker run --rm -it -p 8501:8501 --entrypoint python lukasblecher/pix2tex:api pix2tex/api/run.py &
          aria2c "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo sysctl -w net.core.rmem_max=2500000
          cloudflared tunnel --url $(hostname -I):8501
