name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 10
          pwd
#      - name: Setup Debug Session
#        uses: csexton/debugger-action@master
      
