name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
      - uses: actions/checkout@v2
      - uses: valeriangalliat/action-sshd-cloudflared@v1
